# Build stage
FROM node:20-alpine AS build

WORKDIR /app

# Copy package files first for better caching
COPY package*.json ./
RUN npm ci

# Set build arguments for environment variables
ARG VITE_API_BASE_URL
ARG VITE_WEB_BUILDER_SERVICE_URL
ARG VITE_IMAGINATIVE_SERVICE_URL
ARG VITE_GOOGLE_CLIENT_ID
ARG VITE_MICROSOFT_CLIENT_ID
ARG VITE_MICROSOFT_TENANT_ID
ARG VITE_MICROSOFT_REDIRECT_URI
ARG VITE_GOOGLE_FONTS_API_KEY
ARG VITE_WEBSITE_BUILDER_LICENSE_KEY
ARG VITE_SYSTEM_BASE_DOMAIN
ARG VITE_SYSTEM_IP
ARG VITE_STRIPE_PUBLISHABLE_KEY

# Pass build arguments to environment variables during build
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_WEB_BUILDER_SERVICE_URL=$VITE_WEB_BUILDER_SERVICE_URL
ENV VITE_IMAGINATIVE_SERVICE_URL=$VITE_IMAGINATIVE_SERVICE_URL
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
ENV VITE_MICROSOFT_CLIENT_ID=$VITE_MICROSOFT_CLIENT_ID
ENV VITE_MICROSOFT_TENANT_ID=$VITE_MICROSOFT_TENANT_ID
ENV VITE_MICROSOFT_REDIRECT_URI=$VITE_MICROSOFT_REDIRECT_URI
ENV VITE_GOOGLE_FONTS_API_KEY=$VITE_GOOGLE_FONTS_API_KEY
ENV VITE_WEBSITE_BUILDER_LICENSE_KEY=$VITE_WEBSITE_BUILDER_LICENSE_KEY
ENV VITE_SYSTEM_BASE_DOMAIN=$VITE_SYSTEM_BASE_DOMAIN
ENV VITE_SYSTEM_IP=$VITE_SYSTEM_IP
ENV VITE_STRIPE_PUBLISHABLE_KEY=$VITE_STRIPE_PUBLISHABLE_KEY

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

# Production stage
FROM nginx:stable-alpine

# Copy built assets from build stage
COPY --from=build /app/dist /usr/share/nginx/html

# Copy nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Health check
HEALTHCHECK --interval=30s --timeout=3s \
  CMD wget --quiet --tries=1 --spider http://127.0.0.1/ || exit 1

CMD ["nginx", "-g", "daemon off;"]
